apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: MAIN_MICROSERVICE_PORT
               valueFrom:
                 secretKeyRef:
                   name: inctagram-backend-main-production-config-secret
                   key: MAIN_MICROSERVICE_PORT
             - name: OAUT_GITHUB_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: inctagram-backend-main-production-config-secret
                   key: OAUT_GITHUB_CLIENT_ID
             - name: OAUT_GITHUB_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: inctagram-backend-main-production-config-secret
                   key: OAUT_GITHUB_CLIENT_SECRET
             - name: OAUT_GOOGLE_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: inctagram-backend-main-production-config-secret
                   key: OAUT_GOOGLE_CLIENT_ID
             - name: OAUT_GOOGLE_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: inctagram-backend-main-production-config-secret
                   key: OAUT_GOOGLE_CLIENT_SECRET
             - name: RECAPTCHA_SERVER_KEY
               valueFrom:
                 secretKeyRef:
                   name: inctagram-backend-main-production-config-secret
                   key: RECAPTCHA_SERVER_KEY
             - name: DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: inctagram-backend-main-production-config-secret
                   key: DATABASE_URL
